Streamline log output

diff --git a/watcherd b/watcherd
--- a/watcherd
+++ b/watcherd
@@ -29,7 +29,7 @@ MY_DATE="2022-12-17"
 MY_URL="https://github.com/devilbox/watcherd"
 MY_AUTHOR="cytopia <cytopia@everythingcli.org>"
 MY_GPGKEY="0xA02C56F0"
-MY_VERSION="1.0.4"
+MY_VERSION="1.0.5"
 MY_LICENSE="MIT"
 
 # Default settings
@@ -152,11 +152,11 @@ function trigger() {
 		if [ "${changes}" -eq "1" ]; then
 			if eval "${action}"; then
 				if [ "${verbose}" -gt "0" ]; then
-					printf "%s: [%s] [OK]  %s succeeded: %s\\n" "${MY_NAME}" "$( date '+%Y-%m-%d %H:%M:%S' )" "TRIGGER" "${action}"
+					printf "%s: [%s] [OK]  %s succeeded: %s\\n" "${MY_NAME}" "$( date '+%Y-%m-%d %H:%M:%S' )" "TRG" "${action}"
 				fi
 				return 0
 			else
-				printf "%s: [%s] [ERR] %s failed:    %s\\n" "${MY_NAME}" "$( date '+%Y-%m-%d %H:%M:%S' )" "TRIGGER" "${action}" >&2
+				printf "%s: [%s] [ERR] %s failed:    %s\\n" "${MY_NAME}" "$( date '+%Y-%m-%d %H:%M:%S' )" "TRG" "${action}" >&2
 				# Also return 0 here in order to not abort the loop
 				return 0
 			fi
@@ -283,7 +283,7 @@ fi
 # Initial add
 for d in ${ALL_DIRS}; do
 	# Only CHANGE if adding was successful
-	if action "${d}" "${CMD_ADD}" "ADD:" "${VERBOSE}"; then
+	if action "${d}" "${CMD_ADD}" "ADD" "${VERBOSE}"; then
 		CHANGES=1
 	fi
 done
@@ -311,11 +311,11 @@ if [ "${WATCHER}" = "inotify" ]; then
 	"${WATCH_DIR}" | while read -r output; do
 		d="${output##*\\}"
 		if [[ "${output}" =~ ^(CREATE|MOVED_TO),ISDIR/\\ ]]; then
-			if action "${d}" "${CMD_ADD}" "ADD:" "${VERBOSE}"; then
+			if action "${d}" "${CMD_ADD}" "ADD" "${VERBOSE}"; then
 				trigger "${CMD_TRIGGER}" "1" "${VERBOSE}"
 			fi
 		elif [[ "${output}" =~ ^(DELETE|MOVED_FROM),ISDIR/\\ ]]; then
-			if action "${d}" "${CMD_DEL}" "DEL:" "${VERBOSE}"; then
+			if action "${d}" "${CMD_DEL}" "DEL" "${VERBOSE}"; then
 				trigger "${CMD_TRIGGER}" "1" "${VERBOSE}"
 			fi
 		fi
@@ -342,14 +342,14 @@ else
 
 		# Run ADD command
 		for d in $ADD_DIRS; do
-			if action "${d}" "${CMD_ADD}" "ADD:" "${VERBOSE}"; then
+			if action "${d}" "${CMD_ADD}" "ADD" "${VERBOSE}"; then
 				CHANGES=1
 			fi
 		done
 
 		# Run DEL command
 		for d in $DEL_DIRS; do
-			if action "${d}" "${CMD_DEL}" "DEL:" "${VERBOSE}"; then
+			if action "${d}" "${CMD_DEL}" "DEL" "${VERBOSE}"; then
 				CHANGES=1
 			fi
 		done
